// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB_7JpRNTWWlRUQyYTwOYUgpUNmIeKk9U',
    appId: '1:310120996111:web:5c7b8f39fbd4c95855727a',
    messagingSenderId: '310120996111',
    projectId: 'germinator-a823f',
    authDomain: 'germinator-a823f.firebaseapp.com',
    storageBucket: 'germinator-a823f.appspot.com',
    measurementId: 'G-RWQZLH72GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDetiaVI0Hnum1W-LZmsASxM_Xj514bm0',
    appId: '1:310120996111:android:ce9854108736349355727a',
    messagingSenderId: '310120996111',
    projectId: 'germinator-a823f',
    storageBucket: 'germinator-a823f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhZmFl4bjKdLya4tiv5yXU8HW7UQpZIdM',
    appId: '1:310120996111:ios:69d79bc31e249d9655727a',
    messagingSenderId: '310120996111',
    projectId: 'germinator-a823f',
    storageBucket: 'germinator-a823f.appspot.com',
    iosBundleId: 'com.example.germinator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhZmFl4bjKdLya4tiv5yXU8HW7UQpZIdM',
    appId: '1:310120996111:ios:dc95fb8100ed4b1a55727a',
    messagingSenderId: '310120996111',
    projectId: 'germinator-a823f',
    storageBucket: 'germinator-a823f.appspot.com',
    iosBundleId: 'com.example.germinator.RunnerTests',
  );
}
